# Generated by Django 4.2.20 on 2025-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18, default=0, editable=False, max_digits=28
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallets",
                "indexes": [models.Index(fields=["label"], name="wallet_label_idx")],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=255, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=18, max_digits=28)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(fields=["txid"], name="tx_txid_idx"),
                    models.Index(fields=["wallet"], name="tx_wallet_idx"),
                    models.Index(fields=["created_at"], name="tx_created_at_idx"),
                ],
            },
        ),
    ]
